# /workspaces/supermd-sphinx/.readthedocs.yaml（仓库根目录）
version: 2

# 1. 基础环境配置：安装PDF必需的LaTeX环境 + 合法字段
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # 安装LaTeX完整环境（PDF编译核心依赖）
  apt_packages:
    - texlive-full
    - librsvg2-bin  # 可选：如需转换SVG为PNG则保留

# 2. 规范python.install配置（无Missing key报错）
python:
  install:
    - path: .  # 满足RTD配置规范
      packages:
        - linkify-it-py
        - sphinx
        - sphinx-rtd-theme
        - sphinx-multiversion
        - sphinxcontrib-bibtex
        - sphinx-design
        - cairosvg  # 可选：如需SVG转换则保留
        - pillow    # 可选：如需图片处理则保留

# 3. Sphinx配置（仅用RTD合法字段）
sphinx:
  configuration: sphinx_template/source/conf.py  # 直接指定conf.py完整路径
  builder: html  # RTD强制允许的值，不影响PDF生成
  fail_on_warning: false  # 忽略字体/符号警告，优先编译成功

# 4. 仅输出PDF格式（删除EPUB，核心修改）
formats:
  - pdf

# 5. 核心：切换到模板目录并执行PDF构建（替代working_dir）
commands:
  # 切换到sphinx_template目录，清空旧构建文件，执行PDF编译
  - cd sphinx_template && make clean && sphinx-build -b latex source build/latex && cd build/latex && make