# /workspaces/supermd-sphinx/.readthedocs.yaml（仓库根目录）
version: 2

# 1. 切换到模板目录，匹配环境（保留）
build:
  working_dir: sphinx_template
  os: ubuntu-22.04
  tools:
    python: "3.12"

# 2. 规范python.install配置（解决Missing key报错）
python:
  install:
    - path: .  # 必须指定path，满足RTD配置规范
      packages:
        - linkify-it-py  # 适配模板中的linkify扩展
        - sphinx         # 兜底安装Sphinx核心
        - sphinx-rtd-theme

# 3. 关键：sphinx.builder用RTD允许的值（html），放弃手动指定epub
sphinx:
  configuration: sphinx_template/source/conf.py
  builder: html  # 必须写html/htmldir/dirhtml/singlehtml中的一个
  fail_on_warning: false  # 忽略警告，避免中断

# 4. 仅输出EPUB格式，RTD会自动生成EPUB（核心！）
formats:
  - epub  # RTD会基于HTML构建结果，自动生成EPUB并忽略HTML输出

# 5. 可选：删除多余的commands，用RTD默认逻辑
# （RTD会自动执行：先build html → 再转换为epub → 仅保留epub文件）