version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - texlive-full       # PDF 编译必需

python:
  install:
    - requirements: requirements.txt  # 根目录依赖文件

sphinx:
  configuration: source/conf.py        # 根目录下的 conf.py
  builder: html
  fail_on_warning: false
  language: zh_CN                      # 匹配中文配置

formats:
  - pdf  # 仅生成 PDF