# /workspaces/supermd-sphinx/.readthedocs.yaml（仓库根目录）
version: 2

# 1. 基础环境配置（仅保留RTD合法字段）
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # 移除无效的working_dir，改用commands切换目录

# 2. 规范python.install配置（无Missing key报错）
python:
  install:
    - path: .  # 必须指定path，满足RTD规范
      packages:
        - linkify-it-py
        - sphinx
        - sphinx-rtd-theme
        - sphinx-multiversion
        - sphinxcontrib-bibtex
        - sphinx-design  # 补充模板所有依赖，避免缺失

# 3. Sphinx配置（仅用RTD合法字段）
sphinx:
  configuration: sphinx_template/source/conf.py  # 直接指定conf.py完整路径（无需切换目录）
  builder: html  # RTD强制允许的值，通过校验
  fail_on_warning: false

# 4. 仅输出EPUB格式
formats:
  - epub

# 5. 核心：通过commands切换到模板目录并构建（替代working_dir）
commands:
  # 切换到sphinx_template目录，再执行EPUB构建
  - cd sphinx_template && sphinx-build -b epub source build/epubgit add .readthedocs.yaml