# /workspaces/supermd-sphinx/.readthedocs.yaml（仓库根目录）
version: 2

# 1. 切换到Sphinx模板目录，指定环境
build:
  working_dir: sphinx_template  # 你的Sphinx项目目录
  os: ubuntu-22.04
  tools:
    python: "3.12"  # 匹配环境

# 2. 安装EPUB生成所需依赖（极简版）
python:
  install:
    - packages:
        - sphinx          # Sphinx核心
        - sphinx-rtd-theme# 主题（兼容EPUB渲染）
        - myst-parser     # MD文件解析（必须）

# 3. 仅生成EPUB电子书（关键：builder改为epub）
sphinx:
  configuration: sphinx_template/source/conf.py  # 你的conf.py路径
  builder: epub  # 核心：指定生成EPUB，而非html/pdf
  fail_on_warning: false  # 忽略警告，优先生成成功

# 4. 启用EPUB格式输出（RTD会自动提供下载链接）
formats:
  - epub  # 仅保留EPUB，删除pdf/html