version: 2

# 1. 基础环境配置：安装PDF必需的LaTeX环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - texlive-full
    - librsvg2-bin

# 2. 规范python.install配置（指向sphinx_template下的requirements.txt）
python:
  install:
    - requirements: sphinx_template/requirements.txt  # 适配实际路径

# 3. Sphinx配置（合法字段）
sphinx:
  configuration: sphinx_template/source/conf.py
  builder: html
  fail_on_warning: false

# 4. 仅输出PDF格式
formats:
  - pdf

# 5. 编译命令
commands:
  - cd sphinx_template && make clean && sphinx-build -b latex source build/latex && cd build/latex && make